### ISSUE TITLE
Compilation broken on and Mac and if PATHIE_ASSUME_UTF8_ON_UNIX

### ISSUE THREAD

**Issue by XapaJIaMnu** [Quintus/pathie-cpp#10]
Hey,

Compilation is broken on MAC due to Mac erroneously falling in the into the BSD case of many ifdefs, because it MacOS evolved on BSD. __APPLE__ is more similar to modern linux than to BSD and most of the `#ifdef` sections that are linux only should be used for apple. I have a pull request that does this and fixes the few corner cases where apple requires a different codepath.

Compilation would also fail if `PATHIE_ASSUME_UTF8_ON_UNIX` because of:

https://github.com/Quintus/pathie-cpp/blob/master/src/pathie.cpp#L185
https://github.com/Quintus/pathie-cpp/blob/master/src/pathie.cpp#L210

Those functions do not define `char* fsencoding` in the case that this define is set, which will result in a compilation error due to this variable being used later on in the return statement. Even if this codepath is never reached during execution, this is undefined behaviour in C++ and any modern compiler will complain. Moving the `char * fsencoding` definition outside of the `ifdef` fixes this issue.

Cheers,

Nick

**Comment by XapaJIaMnu** [comment]
Should be fixed by #11

**Comment by Quintus** [comment]
> Those functions do not define char* fsencoding in the case that this define is set, which will result in a compilation error due to this variable being used later on in the return statement.

Ouch. That happens when adding functionality one does not use oneself. Well cought, and thanks for fixing.

>  Even if this codepath is never reached during execution, this is undefined behaviour in C++ and any modern compiler will complain.

I don't think it's undefined behaviour. It's just wrong, invalid C++ and should not compile (not even on old compilers). My bad.

See my comments in the PR for the rest.

**Comment by Quintus** [comment]
Superseded by #11.
