### ISSUE TITLE
sanitize() does not handle Windows UNC paths

### ISSUE THREAD

**Issue by frankseide** [Quintus/pathie-cpp#14]
Hi, I noticed that `sanitize()` does not seem to recognize Windows UNC paths.

It seems to work with the modification below. My apologies for not having time to write this code prettily and prepare a proper PR with tests etc. Just want to report the issue.
```
void Path::sanitize()
{
  bool isWindowsUNCPath = m_path.c_str()[0] == '\\' && m_path.c_str()[1] == '\\'; // UNC path

  // Replace any backslashes \ with forward slashes /.
  size_t cur = string::npos;
  while ((cur = m_path.find("\\")) != string::npos) { // assignment intended
    m_path.replace(cur, 1, "/");
  }

  // Replace all double slashes // with a single one
  // Except for the first position, which would be a Windows UNC path
  cur = string::npos;
  while ((cur = m_path.find("//", isWindowsUNCPath ? 1 : 0)) != string::npos) { // assignment intended
    m_path.replace(cur, 2, "/");
  }
```

**Comment by Quintus** [comment]
Thank you for the hint. I haven't even thought of UNC pathes when I wrote that function. Your contribution is appreciated, I see what I'll make of your code snippet.

**Comment by Quintus** [comment]
If `m_path` is of zero length (default constructor of `Pathie::Path`) your suggestion is going to segfault. I have that fixed in my own version of it.

UNC pathes are Windows-specific I think. I'm going to wrap the code in an `#ifdef _WIN32` thus, otherwise a Linux user is going to be probably surprised why `//` is valid at the beginning of a path.

**Comment by frankseide** [comment]
Thanks! Yes, my code was a sketch. A more correct version would not use `c_str()` but just test the length and then access the string via `operator[]()`.

However, just out of curiosity, why would it segfault? Even if the string is empty, `c_str()` will exist and point to a single 0 character, which is a valid memory address and value in a C string. Due to short-circuit evaluation of `&&` it should not attempt to access the second character if the first one is not `\`. And if it is, the second character is always a valid memory address again, even for a length-1 string where it would contain a 0. (That's why I used the `c_str()` construct in the first place, but that's nevertheless a poor justification for doing that when it's more direct to just check the length.)

Thanks for looking into this!

**Comment by Quintus** [comment]
> However, just out of curiosity, why would it segfault?

You are right. Short-circuiting in effect! My bad.

> but just test the length and then access the string via operator[]().

That's what I'm doing now.

> Thanks for looking into this!

You're welcome.

**Comment by Quintus** [comment]
Problem should be fixed now.
