### ISSUE TITLE
Recursive operator++

### ISSUE THREAD

**Issue by oktonion** [Quintus/pathie-cpp#15]
Holly Bjarne, "Same as the other operator++()"???

https://github.com/Quintus/pathie-cpp/blob/5ccc2b033efe6abd12f4ed2fd549a204978cd65c/src/entry_iterator.cpp#L178-L182

Please change to

```cpp
/// Same as the operator++(int).
entry_iterator& entry_iterator::operator++()
{
  return (operator++(0)); // the 'other' operator++ is int, be careful!
}
```

**Comment by Quintus** [comment]
Heh, nice spot. I almost always use postfix-increment, thus I didn't catch the problem. The problem is only triggered by prefix increment. I'm going to fix it quickly.
