### ISSUE TITLE
Add dll path like exe path doing.

### ISSUE THREAD

**Issue by vega0** [Quintus/pathie-cpp#18]
Add method to determine the library path is called from. I think it will be helpful for some reasons. Best regards

**Comment by Quintus** [comment]
Am 21. Oktober 2019 um 14:25 Uhr -0700 schrieb Nightmare0:
> Add method to determine the library path is called from. I think it
> will be helpful for some reasons. Best regards

I'm sorry, I don't understand. What do you mean? Can you give an example
of what you would like Pathie to do?

-- 
Blog: https://mg.guelker.eu

**Comment by vega0** [comment]
> Am 21. Oktober 2019 um 14:25 Uhr -0700 schrieb Nightmare0:
> Add method to determine the library path is called from. I think it will be helpful for some reasons. Best regards
> I'm sorry, I don't understand. What do you mean? Can you give an example of what you would like Pathie to do?
> […](#)
> -- Blog: https://mg.guelker.eu
`Pathie::Path` exepath    = Pathie::Path::exe();`
This is determination exe path file way, so if i called something from dynamic link library or shared object, i have no methods to determine library path instead of exe path, hmm..

`Pathie::Path exepath    = Pathie::Path::library_path();`

**Comment by Quintus** [comment]
Am 31. Oktober 2019 um 23:21 Uhr -0700 schrieb Nightmare0:
> This is determination exe path file way, so if i called something from
> dynamic link library or shared object, i have no methods to determine
> library path instead of exe path, hmm..

So, you want to determine the path to the shared object library Pathie
was loaded from? You are right, this is currently not possible with
Pathie.

I have conducted some research and it looks as if this is possible,
but not straightforward. On Linux, one has to open the object with
dlopen(3) and then look up the path information with dlinfo(3),
whereas on Windows, one opens the DLL with LoadLibraryW() and then
extracts the path name with GetModuleFileNameW().

However, there's a problem. In both cases it is assumed that the
library you want information about has not yet been loaded. Pathie
however *has* been loaded when you call this hypothetical new
function. Pathie also does not even have a way to determine the
relative file name it has been loaded from.

I have no idea how to retrieve a pointer suitable for either dlinfo(3)
or GetModuleFileNameW() for an already loaded executable. In addition,
pathie may have been statically linked, in which case there is no use
for this hypothetical new function. All that would be possible is to
provide a function that takes an OS-specific pointer which is then
forwarded to dlinfo()/GetMOduleFileNameW(), but that kind of defeats
the purpose of a cross-platform library like Pathie.

This chicken-egg problem makes me think that the function you request
is out of scope for Pathie. Pathie cannot know how it has been loaded
into the executable -- statically linked, dynamically linked, or
linked at runtime with dlopen/LoadLibrary. If you depend on this
information, use your OS' facilities. Load pathie with dlopen(3)
(Linux) or LoadLibrary() (Win32) and then use the functions provided
by the system to retrieve the path information.

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment]
Closing for the reasons given.
